### ISSUE TITLE
general introduction slides

### ISSUE THREAD

**Issue by jkrbs** [fsr/nerd101#5]
Introduction.

- why have we created this event
- why do we think its important
- brief overview on the roadmap

**Comment by jkrbs** [comment]
maybe @Feliix42 would help creating them in the next days

**Comment by Feliix42** [comment]
Can either try to allocate some time for this today or we two get together tomorrow/on Tuesday to throw some slides together

**Comment by jkrbs** [comment]
I'd prefer monday or tuesday lunch time
